title: Lean Tutorial
description: The tutorial for Lean4 used for our seminar. 
lsi: false
safe: true
source: /
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
